
export const CURRENT_VALUE = "CURRENT_VALUE";
export const COMBINE_INPUTS = 'COMBINE_INPUTS';
export const CALCULATED_VALUE = "CALCULATED_VALUE";
export const CLEAR_COMBINED_INPUTS = "CLEAR_COMBINED_INPUTS";
export const UPDATE_PREVIOUS_VALUE = "UPDATE_PREVIOUS_VALUE";
export const CHANGE_FIRST_VALUE_TO_NON_ZERO_NUMBER = "CHANGE_FIRST_VALUE_TO_NON_ZERO_NUMBER";
export const FIRST_NON_ZERO_VALIDATION_TRUE = "FIRST_NON_ZERO_VALIDATION_TRUE";