
export const CHANGE_DISPLAY_UPPER = "CHANGE_DISPLAY_UPPER";
export const CURRENT_VALUE = "CURRENT_VALUE";
export const  COMBINE_INPUTS = 'COMBINE_INPUTS';
export const CALCULATED_VALUE = "CALCULATED_VALUE";
export const CLEAR_COMBINED_INPUTS = "CLEAR_COMBINED_INPUTS";