
export const CURRENT_VALUE = "CURRENT_VALUE";
export const COMBINE_INPUTS = 'COMBINE_INPUTS';
export const CALCULATED_VALUE = "CALCULATED_VALUE";
export const CLEAR_COMBINED_INPUTS = "CLEAR_COMBINED_INPUTS";
export const UPDATE_PREVIOUS_VALUE_2_LENGTH = "UPDATE_PREVIOUS_VALUE_2_LENGTH";
export const UPDATE_PREVIOUS_VALUE_GREATER_THAN_2_LENGTH = "UPDATE_PREVIOUS_VALUE_GREATER_THAN_2_LENGTH";
export const CHANGE_FIRST_VALUE_TO_NON_ZERO_NUMBER = "CHANGE_FIRST_VALUE_TO_NON_ZERO_NUMBER";
export const FIRST_NON_ZERO_VALIDATION_TRUE = "FIRST_NON_ZERO_VALIDATION_TRUE";
export const POP_VALUE_COMBINED_INPUTS = "POP_VALUE_COMBINED_INPUTS";
export const DECIMAL_EXISTS_TRUE = "DECIMAL_EXISTS_TRUE";
export const DECIMAL_EXISTS_FALSE = "DECIMAL_EXISTS_FALSE";
export const UPDATE_COMBINED_INPUTS_TO_LOG_EQUALS = "UPDATE_COMBINED_INPUTS_TO_LOG_EQUALS";